apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgBJt6D1NlBP4tFHwcociYvaiF3nutD3dHjViAwfUC0EFWL0oCRz88bICq0zP2WsyNUyZJumo+yy3fbDIMUHy54KBwavX1g9V1da1AEY0DzxzLyWKjaKd3SYnU/vfHnAiuVQMjFc1VXGH/4W8T20dBN1ktG1huZxvFqKJkXkrglQ7KuatUGhZqS3HqrNph1HqGojx2ZRpbNnX3RDjLHh0t4MWpglawNvHAGRFaqEFaChrR5eqUvOf74OBOrQL3D8ZsEe8pERARYBwsnPiISSVBV7/ub/zHYYc40afkM5yDISwqZM729wSFVevXBoXjYQWFBQ0Xj73X1vIk2OuqepQ3+oDy2O2lcARtPErPoW+825YclVZhBBdbw1PUFiyNyoShGBBkvZoaTcVG03VZZgULIFTe7826cG52V3Vp/9re48UtgqcJ75u1cTfTm2QYNE+ROytqBl7ovLfjzy74mEvDpxRb0zuBEA9CTYnO85ffuSlpJQLvyY+XWbpHsHS9WD7hvIf+vk0dNtlVgYKhfyGhZ7dFTYcIPHkE3d0icmJ7aS0uaZN0qjNewG+9wZAuSkyrCGqdYkRPAsVGmTPMOUobR5k1NPwofkNNnIvJKcyBQIT2kaG8laUJRbL0/vaPI9h4bj01G3uL3+E/mLUm2lTSBYUKv/iG3VpkXtV+z59HS5PILAUA7sCb/hD+twFDokKDk/M58F+3uL1eA0xCFJ1BeQCejVBD0XEhWcfAFvuWhYcNeS+acZS5rzcg==
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

